version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: forum_db
      MYSQL_USER: forum_user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - D:\docker\mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.0
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - D:\docker\redis-data:/data:rw
    networks:
      - app-network
    command: redis-server --requirepass redis123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s

  auth-service:
    build:
      context: .
      dockerfile: dashliving-auth-svc/Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/forum_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: forum_user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis123
      SERVER_PORT: 8081
    networks:
      - app-network

  gateway-service:
    build:
      context: .
      dockerfile: dashliving-gateway-svc/Dockerfile
    container_name: gateway-service
    restart: always
    depends_on:
      - auth-service
      - forum-service
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/forum_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: forum_user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis123
      SERVICES_AUTH_URL: http://auth-service:8081
      SERVICES_FORUM_URL: http://forum-service:8082
    networks:
      - app-network

  forum-service:
    build:
      context: .
      dockerfile: dashliving-forum-svc/Dockerfile
    container_name: forum-service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/forum_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: forum_user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis123
      SERVER_PORT: 8082
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
