name: Build and Push Docker Images

on:
  push:
    branches:
      - TomLocal
      - DashLivingRefactor
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          export TAG=${{ github.sha }}
          export LATEST_TAG=latest
          export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
          
          docker build -t $DOCKER_HUB_USERNAME/forum-app:$TAG -t $DOCKER_HUB_USERNAME/forum-app:$LATEST_TAG .
          
          docker push $DOCKER_HUB_USERNAME/forum-app:$TAG
          docker push $DOCKER_HUB_USERNAME/forum-app:$LATEST_TAG
