name: deploy to EC2

permissions:
  actions: read
  contents: read
  id-token: write

on:
  workflow_run:
    workflows: ["pre-deploy"]
    branches: [TomLocal]
    types: [completed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print workflow_run info
        run: |
          echo "是否触发：工作流已被触发！"
          echo "前置工作流结论：${{ github.event.workflow_run.conclusion }}"
          echo "前置工作流分支：${{ github.event.workflow_run.head_branch }}"
          echo "前置工作流提交：${{ github.event.workflow_run.head_sha }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          TAG=${{ github.event.workflow_run.head_sha }}
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set +x
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            set -x
            
            cd /home/ec2-user/dashliving
            
            docker-compose pull
            
            docker-compose up -d
            
            docker system prune -af