name: Test Deploy Trigger

permissions:
  actions: read

on:
  workflow_run:
    workflows: [ "pre-deploy" ]  # 替换为pre-deploy的实际name
    branches: [ TomLocal ]
    types: [ completed ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print Trigger Info
        run: |
          echo "Pre-deploy conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Pre-deploy branch: ${{ github.event.workflow_run.head_branch }}"