name: pre-deploy

on:
  push:
    branches: [ TomLocal ]
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Docker & Prepare Directories
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
            sudo yum install -y yum-utils device-mapper-persistent-data lvm2
            sudo yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
          
            sudo yum install -y docker-ce docker-ce-cli containerd.io
            sudo systemctl enable --now docker
            sudo usermod -aG docker $USER
          
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          
            sudo mkdir -p /data/docker/mysql-data /data/docker/redis-data /home/ec2-user/dashliving
            sudo chmod -R 777 /data/docker /home/ec2-user/dashliving
          
            docker --version && docker-compose --version && ls -ld /data/docker/mysql-data /data/docker/redis-data /home/ec2-user/dashliving
          EOF
